export const SIGNUP_CHANGE_EMAIL = 'SIGNUP_CHANGE_EMAIL'

export const SIGNUP_CHANGE_PASSWORD = 'SIGNUP_CHANGE_PASSWORD'

export const SIGNUP_CHANGE_CONFIRMPASSWORD = 'SIGNUP_CHANGE_CONFIRMPASSWORD'

export const SIGNUP_REGISTER_NEWUSER = 'SIGNUP_REGISTER_NEWUSER'
